### ISSUE TITLE
How to perform single-user installation?

### ISSUE THREAD

**Issue by x-yuri** [rvm/rvm1-ansible#101]
The `README.md` says this is what's needed:

```
rvm1_install_flags: '--auto-dotfiles --user-install'
rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
```

Also, it says:

> A quick note about rvm1_user
> 
> In some cases you may want the rvm folder and its files to be owned by a specific user instead of root. Simply set rvm1_user: 'foo' and when ruby gets installed it will ensure that foo owns the rvm directory.

But when not specifying `rvm1_user`, it's gonna be `root`. And if it's root, `ansible_ssh_user` won't be able to install gems, create gemsets. Or so I think. Am I wrong?

**UPD** And `rvm` is sourced for `root`, not for `ansible_ssh_user`.

**Comment by lpaulmp** [comment]
The readme was updated, I closing this issue but feel free to re-open.
