### ISSUE TITLE
Detect if rubies are installed doesn't look at the correct RVM when doing a user install

### ISSUE THREAD

**Issue by oscarhost** [rvm/rvm1-ansible#102]
become_user isn't called when checking which rubies are installed. This causes the module to think ruby is already installed for a user if the root user already has it installed.

In "tasks/rubies.yml"

> - name: Detect if rubies are installed  
>   command: '{{ rvm1_rvm }} {{ item }} do true'  
>   changed_when: False  
>   failed_when: False  
>   register: detect_rubies  
>   with_items: '{{ rvm1_rubies }}'  
>   when: rvm1_rubies

Should be:

> - name: Detect if rubies are installed  
>   command: '{{ rvm1_rvm }} {{ item }} do true'  
>   changed_when: False  
>   failed_when: False  
>   register: detect_rubies  
>   with_items: '{{ rvm1_rubies }}'  
>   become: yes  
>   become_user: '{{ rvm1_user }}'  
>   when: rvm1_rubies

**Comment by lpaulmp** [comment]
this was fixed in the last releases. https://github.com/rvm/rvm1-ansible/blob/master/tasks/main.yml#L8-L11
