### ISSUE TITLE
Allow skipping bundler installation

### ISSUE THREAD

**Issue by chadoh** [rvm/rvm1-ansible#103]
I do not need bundler. If you'd like, I can add a `when:` condition to the "install bundler" step so that people can opt out of it.

**Comment by lpaulmp** [comment]
@chadoh Sorry for late response I'll take a look.

**Comment by pvlltvk** [comment]
@lpaulmp So, what about skipping bundler installation? I think that it will be useful feature.

**Comment by pkuczynski** [comment]
Sure, why not. If its optional, it doesn't hurt. @chadoh can you come up with a PR?

**Comment by chadoh** [comment]
I no longer need this personally and therefore don't feel very motivated to carve out time for it. I don't mind if this is closed.

**Comment by pvlltvk** [comment]
@pkuczynski  I will do it

**Comment by pkuczynski** [comment]
@chadoh fair enough. Thanks for the idea anyway! :)
@pvlltvk sure, I will keep it open for you...

**Comment by pvlltvk** [comment]
@pkuczynski  I've just created PR https://github.com/rvm/rvm1-ansible/pull/110

**Comment by lpaulmp** [comment]
@pkuczynski thanks for the contribution I'm closing this issue.
