### ISSUE TITLE
Create a new release and publish in ansible.

### ISSUE THREAD

**Issue by lpaulmp** [rvm/rvm1-ansible#112]
Create a new release since there are some commits that are just in master and then publish those changes in ansible galaxy.

**Comment by pkuczynski** [comment]
I will have a look at this shortly...

**Comment by lpaulmp** [comment]
I'm having some issues to create a new release in ansible galaxy, seems some permission is missing. I requested permission to the owner of the rvm org to allow ansible galaxy access.

**Comment by pkuczynski** [comment]
This should be solved now.

**Comment by lpaulmp** [comment]
Thanks for your help @pkuczynski The last ansible version `v1.3.9` is online.
