### ISSUE TITLE
Ansible Galaxy imports failing?

### ISSUE THREAD

**Issue by geerlingguy** [rvm/rvm1-ansible#148]
When I view the role on Galaxy (https://galaxy.ansible.com/rvm_io/ruby/), I notice that the most recent imports have been failing:

<img width="732" alt="screen shot 2017-04-18 at 10 33 55 am" src="https://cloud.githubusercontent.com/assets/481677/25139342/95ed12a4-2422-11e7-8b17-1cd1ff323d4a.png">

Version 2.0.0 is at least in Galaxy, so that's not a huge deal, but I thought I'd point it out in case the next release doesn't get picked up.

**Comment by geerlingguy** [comment]
I wonder if it might be a formatting issue in `main.yml`: the 'company' might need to be set to an empty string if that's causing a yaml parsing error (https://github.com/rvm/rvm1-ansible/blob/master/meta/main.yml#L5).

**Comment by geerlingguy** [comment]
Actually, it looks like it might be `galaxy_tags` not being set. PR incoming...

**Comment by lpaulmp** [comment]
@geerlingguy Thanks
