### ISSUE TITLE
When installing JRuby, symlinking fails on erb

### ISSUE THREAD

**Issue by tadman** [rvm/rvm1-ansible#154]
It looks like JRuby 9.1 no longer bundles the `erb` binary which causes a failure during the symlink stage if you're not using the `--user-install` option in `rvm1_install_flags`:

```
TASK [rvm_io.ruby : Symlink ruby related binaries on the system path] **********
failed: [dev] (item=erb) => {"failed": true, "item": "erb", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/local/rvm/wrappers/default/erb", "path": "/usr/local/bin/erb", "src": "/usr/local/rvm/wrappers/default/erb", "state": "absent"}

```

To fix this you will need to update the `rvm1_symlink_binaries` variable and remove `erb`, but it's probably worth making the symlink rule "Symlink bundler binaries on the system path" more robust by testing for the existence of the stub before trying to link it through.

What's a bit annoying is this is set in `vars/main.yml` which seems to have a stubbornly high priority.

**Comment by tadman** [comment]
It looks like `testrb` is also toast in Ruby 2.4.x so that should be removed as well.

**Comment by thbar** [comment]
@tadman is it still a pain for you after all those years?

**Comment by tadman** [comment]
@thbar Since I've migrated my workflow to Docker, hasn't been a problem, so can't speak to the Ansible side of things.

**Comment by pkuczynski** [comment]
Then I guess we should close it. If anybody else encounters this, let us know...
