### ISSUE TITLE
Getting 'src file does not exist' for testrb for Symlink ruby binaries task

### ISSUE THREAD

**Issue by geerlingguy** [rvm/rvm1-ansible#157]
It was running fine inside Travis CI for the past few weeks, but suddenly today my builds are failing on this task:

```
TASK [rvm_io.ruby : Symlink ruby related binaries on the system path] **********
changed: [127.0.0.1] => (item=erb)
changed: [127.0.0.1] => (item=executable-hooks-uninstaller)
changed: [127.0.0.1] => (item=gem)
changed: [127.0.0.1] => (item=irb)
changed: [127.0.0.1] => (item=rake)
changed: [127.0.0.1] => (item=rdoc)
changed: [127.0.0.1] => (item=ri)
changed: [127.0.0.1] => (item=ruby)
failed: [127.0.0.1] (item=testrb) => {"failed": true, "item": "testrb", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/local/rvm/wrappers/default/testrb", "path": "/usr/local/bin/testrb", "src": "/usr/local/rvm/wrappers/default/testrb", "state": "absent"}
```

I'm going to try to see if there were any changes that could've affected rvm_io.ruby installation on my end, but I can't recall anything, so posting this issue in case other people are running into the same issue.

**Comment by geerlingguy** [comment]
Confirmed with a fresh local build too—I have in my playbook configuration:

```yaml
rvm1_rubies: ['ruby-2.3.4']
```

**Comment by geerlingguy** [comment]
My last successful build was using the same ruby version, 5 days ago, and in the logs it seems that testrb _did_ exist then:

```
TASK [rvm_io.ruby : Symlink ruby related binaries on the system path] **********
changed: [127.0.0.1] => (item=erb)
changed: [127.0.0.1] => (item=executable-hooks-uninstaller)
changed: [127.0.0.1] => (item=gem)
changed: [127.0.0.1] => (item=irb)
changed: [127.0.0.1] => (item=rake)
changed: [127.0.0.1] => (item=rdoc)
changed: [127.0.0.1] => (item=ri)
changed: [127.0.0.1] => (item=ruby)
changed: [127.0.0.1] => (item=testrb)
```

So maybe the rvm.io package itself got messed up at some point?

**Comment by geerlingguy** [comment]
As a workaround, I was going to use:

```yaml
rvm1_symlink_binaries:
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'
  # - 'testrb'
```

...but since that variable is defined in `vars/main.yml` it's not easily overridden (unless you try passing in the entire array via `--extra-vars` on the command line, which is really messy :/

**Comment by geerlingguy** [comment]
Checking:

  - https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.3.tar.bz2
  - https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.4.tar.bz2
  - https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.4.1.tar.bz2

... none of these had `testrb` in their bin directories :(

**Comment by geerlingguy** [comment]
So, it looks like upstream, the `testrb` file is not built/included anymore after this commit https://github.com/rvm/gem-wrappers/commit/8a355fd0925d34f7e1b7cd9b299eaf07d62bd92a — see also https://github.com/rvm/rvm/issues/4104

**Comment by geerlingguy** [comment]
PR at least fixes the problem. It might also be nice to have the variable itself moved into `defaults/main.yml` so it can be overridden in the future.

**Comment by lpaulmp** [comment]
@geerlingguy thanks for your contribution, this sounds reasonable - allow overwrite `rvm1_symlink_binaries`.
I'm improving a bit the test for different distros since are reported bugs which the current tests aren't able catch.
