### ISSUE TITLE
Automatic Install ree

### ISSUE THREAD

**Issue by buildadmin** [rvm/rvm1-ansible#166]
Installing Ruby EE on RVM:

https://rvm.io/interpreters/ree

I tried installing ree 18.7 with:

```
    rvm1_rubies: ['ree_1.8.7']
    rvm1_install_flags: '--auto-dotfiles'
    rvm1_install_path: /usr/local/rvm
    rvm1_bundler_install: False
    rvm1_user: root
```

but got this error:

`changed: [rs] => (item={'_ansible_parsed': True, 'stderr_lines': [u'Unknown ruby interpreter version (do not know how to handle): ree_1.8.7.', u'Unknown ruby interpreter version (do not know how to handle): ree_1.8.7.', u'Ruby ree_1.8.7 is not installed.'], '_ansible_item_result': True, u'end': u'2018-03-07 19:27:03.254398', '_ansible_no_log': False, u'stdout': u'', u'cmd': [u'/usr/local/rvm/bin/rvm', u'ree_1.8.7', u'do', u'true'], u'msg': u'non-zero return...`

How can I install ree with this role?

**Comment by buildadmin** [comment]
I ended up using:

```rvm1_rubies: ['ree']```

I had to modify the original role here:

rubies.yml
```- name: Symlink ruby related binaries on the system path
  file:
    state: 'link'
    src: '{{ rvm1_install_path }}/wrappers/default/{{ item }}'
    dest: '{{ rvm1_symlink_to }}/{{ item }}'
    owner: '{{ root_user }}'
    group: '{{ root_group }}'
  when: not '--user-install' in rvm1_install_flags
  with_items: '{{ rvm1_symlink_binaries }}'
  ignore_errors: yes```

because the rake symlinking fails:
```ailed: [rs] (item=rake) => {"changed": false, "item": "rake", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /usr/local/rvm/wrappers/default/rake", "path": "/usr/local/bin/rake", "src": "/usr/local/rvm/wrappers/default/rake", "state": "absent"}```

**Comment by thbar** [comment]
@buildadmin `ree_1.8.7` will not work, but `ree-1.8.7` will. That said this is an unsupported version afaik, which should not be deployed nowadays - you are exposed to numerous security issues!

**Comment by thbar** [comment]
@pkuczynski I suggest closing this one (I don't have the rights to), since 1.8.7 is not maintained anymore & have been for years.

**Comment by pkuczynski** [comment]
Agree!
