### ISSUE TITLE
gpg not found on macos vm

### ISSUE THREAD

**Issue by bbtdev** [rvm/rvm1-ansible#167]
Hello,
I'm running the role from macos to 2 VMs, one ubuntu, the other macos. The ubuntu succedes,the macos fails. If I try gpg directly on the vm it works though, so I don't really understand where is the problem.

fatal: [192.168.33.11]: FAILED! => {"attempts": 5, "changed": false, "cmd": "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3", "msg": "[Errno 2] No such file or directory", "rc": 2}

fatal: [192.168.33.11]: FAILED! => {"changed": true, "cmd": "curl -sSL https://rvm.io/mpapis.asc | gpg --import -", "delta": "0:00:00.395347", "end": "2018-06-26 15:14:42.504547", "msg": "non-zero return code", "rc": 127, "start": "2018-0
6-26 15:14:42.109200", "stderr": "/bin/sh: gpg: command not found\ncurl: (23) Failed writing body (0 != 2750)", "stderr_lines": ["/bin/sh: gpg: command not found", "curl: (23) Failed writing body (0 != 2750)"], "stdout": "", "stdout_lines
": []}

 { 
  role: rvm_io.ruby,
  tags: ruby,
  become: yes,
  rvm1_rubies: ['ruby-2.2.5','ruby-2.3.1'],
  rvm1_install_flags: '--auto-dotfiles', 
  rvm1_install_path: /usr/local/rvm,
  rvm1_user: root
}

Anyone has any ideas?

**Comment by lpaulmp** [comment]
This roles just support Linux base distros.

**Comment by bbtdev** [comment]
No plans for macos?

**Comment by caitlin615** [comment]
I'm not sure if this will help, but I found that (assuming you have gpg installed via brew), adding `export PATH=$PATH:/usr/local/bin` to the user's `.bashrc` fixed this problem for me.
