### ISSUE TITLE
Role install instructions on Galaxy incorrect

### ISSUE THREAD

**Issue by geerlingguy** [rvm/rvm1-ansible#176]
I have traditionally used `ansible-galaxy install rvm_io.ruby` to install this role... and that still works. But if you go to the Galaxy role page for this role (https://galaxy.ansible.com/rvm/ruby), it shows:

    ansible-galaxy install rvm.ruby

...which does _not_ work. You have to still use rvm_io for the namespace. This may be an upstream issue with Galaxy.

**Comment by ctorgalson** [comment]
Looks like this may have been corrected at Galaxy:

![ansible_galaxy](https://user-images.githubusercontent.com/1063424/44954794-a7567500-aea8-11e8-8f74-0c4c810f1002.png)

**Comment by geerlingguy** [comment]
It looks like it was just changed and is now back to:

    ansible-galaxy install rvm.ruby

Closing this issue.
