### ISSUE TITLE
readme specifies root for multiuser installs which rvm docs warn against.

### ISSUE THREAD

**Issue by coldnebo** [rvm/rvm1-ansible#177]
rvm1-ansible [roles section](https://github.com/rvm/rvm1-ansible#role-variables):

```
# Set the owner for the rvm directory
# NOTE: If you are doing a ROOT BASED INSTALL then
#       make sure you set rvm1_user to 'root'
rvm1_user: 'ubuntu'
```
[rvm docs](https://rvm.io/support/troubleshooting#sudo):

>The installation process is similar for both installation methods, however, when installing a multi-user configuration, do not run the installer directly as/from the 'root' account! Always use the sudo command from a non-privileged user account. This is due to variables that are different between root's environment and a user's that aren't affected by an EUID change, as well as code checks in the install itself.

There seem to be ways to make this work, but the docs between projects are inconsistent.

**Comment by isikyus** [comment]
rvm1-ansible does use `sudo` as the docs recommend.

The tasks in https://github.com/rvm/rvm1-ansible/blob/master/tasks/main.yml use Ansible's "become" feature, which in turn uses `sudo` to run things as the specified user.

**Comment by pkuczynski** [comment]
@thbar @sfgeorge what do you think? Should we do anything about it or just close it?

**Comment by sfgeorge** [comment]
@isikyus is right.  The become feature is used, which in turn uses sudo.  I believe this can be closed.

**Comment by pkuczynski** [comment]
Thanks for the feedback @sfgeorge. Closing...

**Comment by thbar** [comment]
It's not closed yet apparently, so I'll go ahead and close it @pkuczynski ; but if this comes up again, maybe we can add some documentation with what is here later!
