### ISSUE TITLE
Missing GPG-key

### ISSUE THREAD

**Issue by rnitschelm** [rvm/rvm1-ansible#184]
It seems there is a gpg-key missing at the moment, causing verification to fail.

https://github.com/rvm/rvm1-ansible/blob/1234af8d77f2bd755168f6b38ac5ff7ccf88f171/defaults/main.yml#L41

Actual key: `409B6B1796C275462A1703113804BB82D39DC0E3'`
Expected keys:  `409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

Please also see this (closed) issue on rvm for further information:

https://github.com/rvm/rvm/issues/4518

**Comment by pkuczynski** [comment]
Hey @lpaulmp can u have a look?

**Comment by TheCorp** [comment]
Definitely would like a fix here! thanks 👍

**Comment by pkuczynski** [comment]
PR merged. @lpaulmp do we need to release this or merge is enough?

**Comment by TheCorp** [comment]
A release would be nice if its not a lot of effort.
