### ISSUE TITLE
Installing with --user-install never finishes

### ISSUE THREAD

**Issue by asgerb** [rvm/rvm1-ansible#19]
Whenever I run the role intending to make a user install, the "Install rubies" task never finishes.
Here's the RVM portion of my yml:

```
- role: rvm_io.rvm1-ruby
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
      sudo: no
```

Ansible runs through the previous tasks just fine, but hangs here:

```
TASK: [rvm_io.rvm1-ruby | Install rubies] ************************************* 
```

And it never finishes. Hoping someone out there can help me, maybe I'm just specifying the configuration wrong?

The script is running on Ubuntu 14.04. My machine runs OS X Yosemite with Ansible 1.7.1 and the latest version of the role installed via Ansible Galaxy.

**Comment by jogaco** [comment]
Fed up with manual installation, I gave this a go but got stuck with the same problem.
Ubuntu 16.10.
Task just freezes for hours.
The docs do not seem to provide an instantly working setup, or there's something I missed.

Trying this still no luck:

`ansible-playbook -i hosts.ini ruby_script.yml --user myuser --ask-sudo-pass -v`
```
---
- name: Configure servers with ruby support for single user
  hosts: newservers

  roles:
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.3'],
        rvm1_user: 'myuser',
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_install_path: '/home/{{ ansible_user }}/.rvm',
        sudo: yes
      }
```
And this is the last part of the output I am getting:
```
TASK [rvm_io.ruby : Detect if rubies are installed] ****************************
ok: [46.xxx.xxx.xx] => (item=ruby-2.3.3) => {"changed": false, "cmd": ["/home/myuser/.rvm/bin/rvm", "ruby-2.3.3", "do", "true"], "delta": "0:00:00.378382", "end": "2016-12-02 19:43:03.639547", "failed": false, "failed_when_result": false, "item": "ruby-2.3.3", "rc": 2, "start": "2016-12-02 19:43:03.261165", "stderr": "Ruby ruby-2.3.3 is not installed.", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [rvm_io.ruby : Install rubies] ********************************************
```
Freezes and does not output anything else.
Until I Ctrl-C it:
```
^CProcess WorkerProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
 [ERROR]: User interrupted execution
```
Any help would be appreciated.

**Comment by chusiang** [comment]
I have some error of `Ruby ruby-2.3.3 is not installed`, but it's working with root on Ubuntu 14.04.

```
rvm1_install_flags: '--user-install'
rvm1_user: 'root'
```

**Comment by jogaco** [comment]
I don't think installing with root is a good idea. Check out #127
