### ISSUE TITLE
Install fails with no action detected

### ISSUE THREAD

**Issue by Januson** [rvm/rvm1-ansible#194]
I tried to install RVM with Ruby 2.4.2 according to the example in your README but it failed with an error. I used this definition.

```
- name: Configure servers with ruby support for single user
  hosts: all
  roles:
    - { role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.4.2'],
        rvm1_user: 'vagrant',
    }
```

Here is the error message.

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/home/januson/Projects/xxx.yml': line 96, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - name: Configure servers with ruby support for single user
>   ^ here
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

**Comment by ksz2k** [comment]
@Januson did you fix it? I have same issue
