### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by wytcld** [rvm/rvm1-ansible#202]
Please, when writing up examples, test that they work as given and don't depend on the user knowing the "obvious" things you have left out.

"ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path. ...

"The offending line appears to be:
  - name: Configure server with ruby support for single user
    ^ here"

This is from quite exactly putting one of the example code fragments into the context of a larger, otherwise working script. I'm sure more experienced Ansible users will know why your fragments fail. I have "hosts" defined atop the file, and this section is under "tasks:". Why this should be "no action detected" eludes me. What has the example left out?

**Comment by thbar** [comment]
I do understand your pain. Please note we're all users (including all contributors), and contributors have a very limited bandwidth.

Closing for now, but a PR to correct this would be most welcome!
