### ISSUE TITLE
I don't get it.

### ISSUE THREAD

**Issue by tvw** [rvm/rvm1-ansible#203]
My playbook looks like this:

```yaml
  roles:
    - my_first_role
    - my_second_role
    - my_third_role
```

with a file-system like this:

```
roles/
  my_first_role/
    tasks/
      main.yml
  my_second_role/
    tasks/
      main.yml
  my_third_role/
    tasks/
      main.yml
```

How can I install rvm and some rubies from within one of my roles?

Also the yaml used in the examples looks very strange to me and not very yaml.

**Comment by tchia04** [comment]
You can always use a yaml syntax checker such as this one here to see if it has valid yaml syntax
http://www.yamllint.com/

You can also look at the following link for the yaml syntax
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

**Comment by thbar** [comment]
This sounds like a general Ansible question, more than something specific to the role. I will close for now, but please re-open if you have more interrogations.
