### ISSUE TITLE
Migrate to a new "Continuous Integration as a Service" Platform

### ISSUE THREAD

**Issue by gildegoma** [rvm/rvm1-ansible#223]
Candidates are (very likely): GitHub Actions or Circle CI 

The build approach will remain the same: Run Ansible Playbooks against Docker containers (to cover different operating systems).

To be configured:
- [ ] Per-push Builds for Pull Requests
- [ ] Per-push Builds for Branches
- [ ] Daily Build of `master` Branch

**Note:** This should be added while keeping Travis CI setup active, so it will be quite easy to compare the performances of the different CI platforms.

**Comment by thbar** [comment]
In #234, we moved to GitHub Actions.
