### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by gammarayb** [rvm/rvm1-ansible#227]
`TASK [rvm.ruby : Detect if rubies are installed] ********
[DEPRECATION WARNING]: evaluating 'rvm1_rubies' as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed in 
version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

`TASK [rvm.ruby : Detect if ruby version can be deleted] *******
[DEPRECATION WARNING]: evaluating 'rvm1_delete_ruby' as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be removed
 in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`
 
seems that this issue is already fixed in master but isnt in the current tag.

**Comment by pkuczynski** [comment]
I released the new version yesterday. Sorry for the delay. Closing this one...
