### ISSUE TITLE
Import GPG keys from keyservers] / ipv4.pool.sks-keyservers.net

### ISSUE THREAD

**Issue by libert-xyz** [rvm/rvm1-ansible#228]
OS: Ubuntu 20.04 LTS

Looks like the pool https://sks-keyservers.net/ has been deprecated and it should be removed from the [defaults](https://github.com/rvm/rvm1-ansible/blob/f1500e939361ddedc31772a3a7dfe5f1843fcc4e/defaults/main.yml#L49)

Logs:

`failed: [127.0.0.1] (item=hkp://pool.sks-keyservers.net) => {"ansible_loop_var": "item", "changed": false, "cmd": "gpg --batch --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB", "delta": "0:00:00.364725", "end": "2021-07-16 16:58:37.572822", "item": "hkp://pool.sks-keyservers.net", "msg": "non-zero return code", "rc": 2, "start": "2021-07-16 16:58:37.208097", "stderr": "gpg: keyserver receive failed: No name", "stderr_lines": ["gpg: keyserver receive failed: No name"], "stdout": "", "stdout_lines": []}
`

**Comment by Aevyz** [comment]
Temporary hotfix that might work: https://github.com/rvm/rvm1-ansible/pull/232#issuecomment-1067483852

**Comment by thbar** [comment]
#232 has been merged into master.
