### ISSUE TITLE
CI Builds are not running

### ISSUE THREAD

**Issue by sfgeorge** [rvm/rvm1-ansible#233]
Travis CI Builds are not running, so there is no automated test coverage on PRs.

<img width="857" alt="PR stuck waiting for Travis to run" src="https://user-images.githubusercontent.com/208529/156263586-c491b58f-c5e1-4790-829c-a9a2190c3205.png">

The latest Travis CI build was apparently 1 year ago.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/208529/156263972-17f972b7-d53b-4763-b934-ca4fbcb7338e.png">
https://travis-ci.org/github/rvm/rvm1-ansible/builds

We should either Identify and fix the issue with Travis CI, or move to another suite such as GitHub Actions.

**Comment by sfgeorge** [comment]
It looks like this is due to the following policy changes on Travis to address abusers of the service.

> We love our OSS teams who choose to build and test using TravisCI and we fully want to support that community. However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.). Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.
>
> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> You will not need to change your build definitions when you are pointed to the new plan
> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
> Your account name and VCS provider (like travis-ci.com/github/[your account name] )
> How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
> Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used
[The new pricing model for travis-ci.com – Nov 2, 2020](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#:~:text=Building%20on%20a%20public%20repositories%20only)

So they still support free open-source builds, but with a formal email request and allotment process.

It's a reasonable approach, given the amount of abuse they've received.  And I'm grateful for the generous service they've provided for the open source community for so many years.

But to be honest, my 2 cents are that it's worth it to move over to GitHub Actions where a request/renewal process is not necessary.

**Comment by pkuczynski** [comment]
We should move to github actions like we did with main rvm repo. @sfgeorge can you take it over?

**Comment by sfgeorge** [comment]
Yep! On it 👍

**Comment by sfgeorge** [comment]
Just sharing a quick note.  This is still in-progress and now making good headway.

I'm developing this over on sfgeorge/rvm1-ansible#1 in order to be able to easily run GitHub Actions over on my fork.  Once ready, I'll open a PR on the main repo here.
