### ISSUE TITLE
Allow setting default-used Ruby

### ISSUE THREAD

**Issue by wizonesolutions** [rvm/rvm1-ansible#27]
Can we have an `rvm1_default_ruby`? Right now, the one that gets used by default seems to be somewhat random. I installed `2.1.3` and `1.9.3` and the `1.9.3` got used.

**Comment by nickjj** [comment]
Fixed on master https://github.com/rvm/rvm1-ansible/commit/aefe5b0556c793707dde6ba99f2d23ec27721454.
