### ISSUE TITLE
GPG Key Issues During Fresh Deployment

### ISSUE THREAD

**Issue by GuitarrasDeAmor** [rvm/rvm1-ansible#31]
Piggybacking on this issue: https://github.com/rvm/rvm1-ansible/issues/16
I'm still having this issue on a clean box that doesn't have RVM installed or ruby installed at all. I manually pulled down the keys running the gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 commands for both root and my other user to test that. I get this:

> gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
> gpg: key D39DC0E3: "Michal Papis (RVM signing) mpapis@gmail.com" not changed
> gpg: Total number processed: 1
> gpg: unchanged: 1

This is on a clean server. Another server I already have this installed on works fine - I can rerun the role and it goes through and checks okay, I can also run the command and it gives the output above.

**Comment by nickjj** [comment]
Is it causing the role to not be downloaded?

**Comment by GuitarrasDeAmor** [comment]
Correct: This is the exact error I get.

> TASK: [rvm_io.rvm1-ruby | Import GPG keys] ************************************
> failed: [10.0.1.129] => {"changed": false, "cmd": ["gpg", "--keyserver", "hkp://keys.gnupg.net", "--recv-keys", "D39DC0E3"], "delta": "0:02:00.151892", "end": "2015-02-11 08:17:19.675277", "rc": 2, "start": "2015-02-11 08:15:19.523385"}
> stderr: gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
> gpg: keyserver timed out
> gpg: keyserver receive failed: Keyserver error

> FATAL: all hosts have already failed -- aborting

**Comment by nickjj** [comment]
Ok, @mpapis should be back at the end of the week. He'll look into it.

**Comment by GuitarrasDeAmor** [comment]
Any updates on this?

**Comment by nickjj** [comment]
None. I was hoping @mpapis could look into it because he handles the gpg key related info.

**Comment by mpapis** [comment]
oh sorry I missed the last message when I was deleting all my email (http://niczsoft.com/2015/02/changes-in-my-open-source-life/) - I will look into it in the evening (~4-5h)

**Comment by arnlen** [comment]
Even if the issue referenced above is closed, the problem seems to persist.
I add it here for further mutal investigations : https://github.com/wayneeseguin/rvm/issues/3110

**Comment by UnderGreen** [comment]
Hello guys.
I have workaround: just change rvm1_gpg_key_server to hkp://pgp.mit.edu

**Comment by GuitarrasDeAmor** [comment]
That workaround did not work for me unfortunately @UnderGreen.

**Comment by mateusduboli** [comment]
To solve this I needed to first bypass the key download setting the variable:
`rvm_gpg_key: ''`

And download the keys manually on the machine with:
```
curl -#LO https://rvm.io/mpapis.asc
gpg --import mpapis.asc
```

**Comment by tobijb** [comment]
@UnderGreen solution worked for me in the RVM rvm_io.rvm1-ruby/defaults/main.yml

**Comment by resmall** [comment]
After I got the error, I removed the .gnupg directory, and proceeded as follows:

    rm -rf ~/.gnupg/
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    curl -L https://get.rvm.io | bash -s stable
    source /home/vagrant/.rvm/scripts/rvm
    rvm -v
    rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

**Comment by GuitarrasDeAmor** [comment]
The only solution I've found thus far is to just pull the key with the curl command above and comment out the piece that downloads it in the rvm.yml task.

**Comment by mpapis** [comment]
maybe we could make it an option to pick import instead of server?

**Comment by dinapappor** [comment]
This is also happening on FreeBSD 10.1 with gpg 2.1.2.

**Comment by dinapappor** [comment]
@mpapis or make it optional?

I guess you could add FreeBSD to the list of working platforms as well. Just tried the role (with the gpg commented out though) on a FreeBSD 10.1 instance on ec2.

**Comment by rossinkiwi** [comment]
To get this to work, I had to:
1. Manually ssh to server and execute `gpg --keyserver hkp://pgp.mit.edu --recv-keys D39DC0E3`
2. Set role variable `rvm1_gpg_keys: " "`
Would be nice to get this fixed...:)

**Comment by OddEssay** [comment]
I've had this same problem (Using Vagrant, Ubuntu 14.04) 

@UnderGreen's solution of setting the rvm1_gpg_key_server to hkp://pgp.mit.edu
```
  sudo: yes
  remote_user: vagrant
  vars:
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_gpg_key_server: 'hkp://pgp.mit.edu'
```

**Comment by nichenke** [comment]
Centos 6.6 (vagrant, "chef/centos-6.6") - and `rvm1_gpg_key_server: 'hkp://pgp.mit.edu'` fixed me up.

**Comment by nickjj** [comment]
Seems like setting `rvm1_gpg_key_server: 'hkp://pgp.mit.edu'` is the way to go. Did this fix the issue for anyone else?

**Comment by zephyr-dev** [comment]
Yes (setting `rvm1_gpg_key_server: 'hkp://pgp.mit.edu'`)

**Comment by allomov** [comment]
@nickjj I still have this issue even with settings `rvm1_gpg_key_server: 'hkp://pgp.mit.edu'` var.

**Comment by allomov** [comment]
when I run `gpg --list-keys D39DC0E3`, I've got the following output:
```
pub   4096R/D39DC0E3 2014-10-28
uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
```
So I think that changes from https://github.com/rvm/rvm1-ansible/pull/36 will fix the issue for me.

**Comment by mattmartini** [comment]
One of the issues that I ran into is that while I was able to import the 
RVM Signing key, it was not trusted and therefor getting the new rvm failed.

What you have to do is trust the key, and more specifically you have to trust
the RVM Signing key, not the mater key.

You can follow the steps below to see how this is done.



    $ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
    gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
    gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
    gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
    gpg: next trustdb check due at 2017-01-12
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    
    $ gpg --list-key D39DC0E3
    pub   4096R/D39DC0E3 2014-10-28
    uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
    sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
    
    $ gpg --edit-key D39DC0E3
    gpg (GnuPG) 1.4.19; Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub  4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> key 1
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> trust
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    Please decide how far you trust this user to correctly verify other users' keys
    (by looking at passports, checking fingerprints from different sources, etc.)
    
      1 = I don't know or won't say
      2 = I do NOT trust
      3 = I trust marginally
      4 = I trust fully
      5 = I trust ultimately
      m = back to the main menu
    
    Your decision? 4
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: full          validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ full] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> quit

**Comment by jonathansp** [comment]
Any ideas?
```bash
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
stderr: gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

**Comment by huanzhang** [comment]
I got this error
```
gpgkeys: HTTP fetch error 6: Could not resolve host: keys.gnupg.net; Unknown error
```

**Comment by lpaulmp** [comment]
@huanzhang Could you add more info or run on debug mode -vvvv?

**Comment by huanzhang** [comment]
@lpaulmp Sorry, I forgot to update that I have solved this problem. Actually, this was caused by incorrect DNS configuration of the vm:)

**Comment by lpaulmp** [comment]
Thanks @huanzhang
