### ISSUE TITLE
Curl Dependency (Ubuntu)

### ISSUE THREAD

**Issue by cfoy** [rvm/rvm1-ansible#32]
I'm new to ansible, so forgive me if I'm missing something obvious.

With the standard Vagrant Ubuntu 12.04 image (at least), curl is not installed by default, so rvm installation fails. If I add an apt pkg state=installed for curl to tasks/debian.yml, everything works fine.

Should curl be a dependency (at least for Debian-based systems)?

**Comment by nickjj** [comment]
Which version of the role are you using?

**Comment by cfoy** [comment]
v1.3.4 installed from ansible galaxy

**Comment by nickjj** [comment]
Sorry for the long delay. I wonder if this is specific to vagrant's image. I haven't experienced this elsewhere.

It is a bug nonetheless. I will add curl as a dependency in the next release.

**Comment by nickjj** [comment]
`tasks/debian.yml` hasn't been around for a while now. Are you 100% sure 1.3.4 was being ran?

**Comment by cfoy** [comment]
Sorry for the delay getting back to you. I was using 1.3.4, but I created `tasks/debian.yml` myself.

It looks like it's just the `hashicorp/precise64` image. The `ubuntu/precise64` and `ubuntu/trusty64` images all have curl installed, so it's probably fine to close.

**Comment by nickjj** [comment]
Ok, going to close this. If more people come across missing curl dependencies in other "not really popular but not unheard of" images I will add in the curl dependency.

Thanks.

**Comment by allomov** [comment]
Hey, all.

I've faced this issue today. And it needed some time for debug. I've fixed it by adding `shrikeh.curl` role in dependencies before `rvm1-ansible`.

**Comment by jrodrigosm** [comment]
Hi,

Debian 8 (Jessie) does not come with curl installed by default. In this case the role fails unless I install curl before running the role.

The workaround is pretty simple, I'm just letting you know so that you consider adding curl as a dependency.
