### ISSUE TITLE
is rvm installed?

### ISSUE THREAD

**Issue by d3netxer** [rvm/rvm1-ansible#33]
I ran the rvm1-ansible role, after I started my virtual machine and typed in 'rvm' in the terminal, it outputted:

The program 'rvm' is currently not installed.  You can install it by typing:
apt-get install ruby-rvm

is rvm installed?

**Comment by nickjj** [comment]
- Did you do a system wide or user install?
- What OS?
- Did the ansible run finish successfully?

**Comment by d3netxer** [comment]
I did a system wide install (I didn't change the defaults), this is on Ubuntu 12.04, and Ansible finished without any errors.

After the machine was built I was looking into things, what got rvm working for me was adding rvm.sh to ~/.bashrc 

so I added this task to my Ansible playbook:

- name: add rvm to bashrc
    lineinfile: dest=/home/vagrant/.bashrc line="source /etc/profile.d/rvm.sh"

now I can call rvm automatically after my machine is built.

**Comment by nickjj** [comment]
And for confirmation, before adding that in you were able to run `ruby -v` as well as other ruby-related binaries right?

rvm itself is not symlinked during the install process but the other binaries are. Do you have a use for for manually running rvm on the system?

**Comment by d3netxer** [comment]
I believe I was able to run ruby -v before.

I think I assumed I needed to manually run rvm, but know that I think about it I may not need to.

Thanks for the help.
