### ISSUE TITLE
Painful upgrade from version 1.3.1 to 1.3.7 because of rvm1_install_path change

### ISSUE THREAD

**Issue by adamniedzielski** [rvm/rvm1-ansible#43]
I was trying to upgrade from version 1.3.1 to 1.3.7
I got following error:

```
 (item=ruby-2.2.2) => {"changed": false, "cmd": "/usr/local/rvm/wrappers/ruby-2.2.2/gem list | if ! grep \"^bundler \" ; then /usr/local/rvm/wrappers/ruby-2.2.2/gem install bundler ; fi", "delta": "0:00:00.014864", "end": "2015-04-29 10:14:01.134892", "item": "ruby-2.2.2", "rc": 127, "start": "2015-04-29 10:14:01.120028", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: /usr/local/rvm/wrappers/ruby-2.2.2/gem: No such file or directory
/bin/sh: /usr/local/rvm/wrappers/ruby-2.2.2/gem: No such file or directory
```

I have RVM installed in ```/usr/local/lib/rvm``` because this was the default directory in version in 1.3.1. It was later changed to ```/usr/local/rvm```, but RVM somehow didn't get "reinstalled" to this new directory after updating to 1.3.7. ```/usr/local/rvm/wrappers``` is empty. That's why installing bundler fails.

When I changed ```rvm1_install_path``` back to ```/usr/local/lib/rvm``` installation proceeded without further errors.

**Comment by nickjj** [comment]
I'm going to close this because it's an upgrade issue, not so much a bug.

If it comes up again, maybe we can add docs explain upgrading from an older version.
