### ISSUE TITLE
rvm_rubies must be specified via `ruby-`

### ISSUE THREAD

**Issue by JustinAiken** [rvm/rvm1-ansible#75]
- If you specify `2.2.3`:
  - It will install the ruby and set it as default okay
  - It will fail to install bundler: `/usr/local/rvm/wrappers/2.2.3/gem not found`
- If you specify `ruby-2.2.3`:
  - It uses the correct path:  `/usr/local/rvm/wrappers/ruby-2.2.3/gem`

Not sure if a note it the docs should point that out, or the playbook itself should adjust the input if needed, but thought I'd point it out in case anyone else bumps into it.

**Comment by rjrobinson** [comment]
Updated the readme. #108 Would you like to add anything else?

**Comment by JustinAiken** [comment]
Looks good to me!

**Comment by rjrobinson** [comment]
Cool. looks like it was merged!

**Comment by JustinAiken** [comment]
Fixed by #108

**Comment by pkuczynski** [comment]
I guess it should adapt automatically, especially `rvm install x.x.x` works fine without the `ruby` prefix. However we can keep it as it is for now - so only on the documentation level...
