### ISSUE TITLE
Switch to ruby version

### ISSUE THREAD

**Issue by strarsis** [rvm/rvm1-ansible#81]
When there is another role/playbook/external ansible code that should install a gem,
how can it easily switch to a ruby version to use its gem command?
Does this role offer a command or shortcut for this?

Thank you and
with best regards

**Comment by nickjj** [comment]
The `bundle` and `gem` binaries are symlinked. You should be able to reference them directly from another role.

A full list of available binaries can be found here:
https://github.com/rvm/rvm1-ansible/blob/master/vars/main.yml#L9

**Comment by lpaulmp** [comment]
@strarsis the last comment helped to resolve this issue?

**Comment by strarsis** [comment]
Yes I think so.
