### ISSUE TITLE
Bare variables deprecated

### ISSUE THREAD

**Issue by Heliosmaster** [rvm/rvm1-ansible#89]
`TASK [rvm_io.rvm1-ruby : Detect if rubies are installed] ***********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{rvm1_rubies}}'). This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.`

And others similarly. Tested with Ansible 2.0.1.0
Similar to #86

**Comment by lpaulmp** [comment]
@Heliosmaster are you using the last release?

**Comment by veger** [comment]
Last deprecation warning should be fixed with https://github.com/rvm/rvm1-ansible/pull/124
