### ISSUE TITLE
Update rvm1-ruby role on Ansible Galaxy please

### ISSUE THREAD

**Issue by wunzeco** [rvm/rvm1-ansible#96]
@lpaulmp, @dvanallen, @tarvip, @nickjj 

Hi guys, 

Any chance you could update this role on Ansible Galaxy please? I'm still getting the older version from Galaxy, which doesn't have the latest fixes. 

Many thanks for your help.

**Comment by lpaulmp** [comment]
@wunzeco The last release is now available [v1.3.8](https://galaxy.ansible.com/rvm_io/rvm1-ruby/)
