### ISSUE TITLE
Update min ansible version in meta/main.yml

### ISSUE THREAD

**Issue by arturmartins** [rvm/rvm1-ansible#99]
The commit https://github.com/rvm/rvm1-ansible/commit/d41109ab80a23cf1b8fcd63fcfd806c145a7d465 made this role incompatible with ansible 1.9.

Below the error that I got:
```
ERROR: incompatible parameters ("become", "become_user", "become_pass") 
and sudo params "sudo", "sudo_user", "sudo_pass" in task: Import GPG keys
```

**Comment by lpaulmp** [comment]
@arturmartins could you use an old release please?

**Comment by lpaulmp** [comment]
@arturmartins I close this issue since there are old releases that support ansible 1.9
